# Generated by Django 2.0.5 on 2018-12-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateTimeField()),
                ('country_code', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('wind_speed', models.DecimalField(decimal_places=6, max_digits=12)),
                ('wind_direction_short', models.CharField(max_length=10)),
                ('wind_direction_full', models.CharField(max_length=200)),
                ('wind_direction_degrees', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
    ]
