# Generated by Django 2.0.5 on 2018-12-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0002_auto_20181216_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='APItoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
            ],
        ),
    ]
