# Generated by Django 2.0.5 on 2018-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0004_elementsreturned'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsreturned',
            name='elements',
            field=models.IntegerField(default=10),
        ),
    ]
