# Generated by Django 2.0.5 on 2018-12-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0005_elementsreturned_elements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('country', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=10)),
                ('capital', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='localization',
            unique_together={('city_name', 'latitude', 'longitude', 'country', 'country_code', 'capital')},
        ),
    ]
